name : Test Pytest

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    name: Pytest with Github Actions
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    # runs within your Docker container
    services:
      myport:
        image: nam2312/myimage:1
        # Map port 8080 on the Docker host to port 80 on the nginx container
        ports:
          - 5000:5000
    
    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
          pip install -U pytest
          pytest tests
