name : Test Pytest

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Pytest with Github Actions
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        cd app
        docker build -t flask-api .
        docker run --rm -d -p 5000:5000 flask-api
    - name: test endpoint
      run : |
        pip install -U pytest
        pytest tests
#     # runs within your Docker container
#     services:
#       myport:
#         image: nam2312/myimage:1
#         # Map port 8080 on the Docker host to port 80 on the nginx container
#         ports:
#           - 5000:5000
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: Test with pytest
#       run: |
#           pip install -U pytest
#           pytest tests
